bitcoin-wasm/src/prelude.rs
bitcoin/src/types/script.rs
bitcoin/src/types/txin.rs
core/src/ser.rs
core/src/types/primitives.rs

refactor: remove non-minimal varint handling

---

bip32/src/curve/libsecp.rs
bip32/src/curve/mod.rs
bip32/src/curve/model.rs
bip32/src/curve/rust_secp.rs
bip32/src/derived.rs
bip32/src/enc.rs
bip32/src/keys.rs
bip32/src/lib.rs
bip32/src/model.rs
bip32/src/prelude.rs
bip32/src/xkeys.rs
bitcoin/src/builder.rs
bitcoin/src/enc/encoder.rs
bitcoin/src/nets.rs
bitcoin/src/types/script.rs
bitcoin/src/types/utxo.rs
core/src/builder.rs
core/src/hashes/mod.rs
core/src/nets.rs
ledger-btc/src/app.rs
ledger-btc/src/utils.rs
psbt/src/global.rs
psbt/src/input.rs
psbt/src/lib.rs
psbt/src/output.rs
psbt/src/roles/bip32_signer.rs
psbt/src/roles/finalizer.rs
psbt/src/roles/ledger_signer.rs
psbt/src/schema.rs

- Adds a lazy_static backend to the default backend types
- removes `<'a>` lifetime and backend passing from bip32 keys in PSBT by forcing use of the static backend
- this is technically a feature downgrade, but oh my god it simplifies the experience

refactor: remove lifetime from non-generic bip32 keys

---

bip32/src/curve/model.rs
bip32/src/keys.rs
bitcoins/src/types/txin.rs

Cleans up the Bip32 backend trait

bug: bip32 trait used Bip32Error instead of Self::Error

---

bitcoins/src/builder.rs
bitcoins/src/hashes.rs

I built the docs and noticed these typos

bitcoins: fix some typos

---

ledger/Cargo.toml
ledger/src/transports/hid.rs
ledger/tests/integration.rs

I have verified that this succesfully exchanges packets with the device on osx

bug: fix osx compilation issues

---

bip32/benches/bench.rs
bip32/src/derived.rs
bip32/src/prelude.rs
bitcoins-wasm/Cargo.toml
bitcoins/src/builder.rs
bitcoins/src/enc/encoder.rs
bitcoins/src/hashes.rs
bitcoins/src/lib.rs
bitcoins/src/types/legacy.rs
bitcoins/src/types/script.rs
bitcoins/src/types/witness.rs
core/src/lib.rs
core/src/macros.rs
core/src/ser.rs
ledger-btc/Cargo.toml
ledger-btc/tests/integration.rs
ledger/Cargo.toml
ledger/node_tests/package-lock.json
ledger/node_tests/package.json
litecoins/Cargo.toml
provider/Cargo.toml
provider/src/utils.rs
psbt/Cargo.toml
psbt/src/common.rs
psbt/src/lib.rs
psbt/src/roles/bip32_signer.rs

- Moves useful macros from `bitcoins` to `coins_core`.
- Fix bip32 benches using old API
- Temporary fix for wasm-pack issue (https://github.com/rustwasm/wasm-pack/issues/886)
- `cargo fmt`

chores: #53 - macros to core. fix bip32 bench. fix wasm-pack

---

bitcoins/src/enc/encoder.rs
core/src/prelude.rs
core/src/ser.rs
psbt/src/lib.rs
psbt/src/schema.rs

Allows the caller to choose between 3 modes for `read_seq_from`
TODO

feature: operation modes for read_seq_from

---

handshakes/README.md
handshakes/src/builder.rs
handshakes/src/types/txout.rs

Adds a `README.md` along with a test for the builder API to make sure that the example in the `README` works. Also updates the `Builder.pay_covenant` to not return a `Result`, this makes the builder API more consistent

docs: handshakes

---

bip32/Cargo.toml
bip32/src/derived.rs
bip32/src/macros.rs
bip32/src/xkeys.rs
bip39/Cargo.toml
bitcoins/Cargo.toml
core/Cargo.toml
handshakes/Cargo.toml
ledger-btc/Cargo.toml
ledger-btc/src/app.rs
ledger-btc/src/utils.rs
ledger-btc/tests/integration.rs
ledger/Cargo.toml
litecoins/Cargo.toml
provider/Cargo.toml

- Update crypto traits in bip32
- Make dependencies within the workspace start to use internal paths

Update RustCryptoTraits and workspace deps use internal paths.

---

ledger/src/common.rs

If the Ledger is locked, don't panic, return an error instead.
Currently, trying to connect to the ledger nano x while it is locked causes a panic.

Handle Ledger error 0x6804

---

ledger/Cargo.toml
ledger/README.md
ledger/src/transports/hid.rs

Replaces [hidapi](https://crates.io/crates/hidapi) for [hidapi-rusb](https://crates.io/crates/hidapi-rusb). 
It's a minimal fork, where the only difference is that `hidapi-rusb` takes by default the `libusb` backend built by `rusb.` (feature: `libusb-static-rusb`). This way, it no longer depends on `libudev-dev` or `libusb-1.0-0-dev`.

replace hidapi for hidapi-rusb

---

ledger/Cargo.toml
ledger/src/transports/hid.rs

Resolves #94.
Had to make some debatable decisions on this PR.
1. Error Handling
I'm adding a new variant `InvalidTermuxUsbFd` to `NativeTransportError` because I want to provide a helpful error message. If I simply make use of existing variants, users might just think the platform isn't supported, whereas in fact they're just not invoking the program correctly (must run as sub-process of `termux-usb`, which opens the file descriptor through Java API).
However, adding a new enum variant is technically a source-breaking change (for those exhaustively listing all `NativeTransportError` variants in a `match` expression, though I doubt if anyone would do that). We might need to bump the version straight to 0.7.0 instead of 0.6.1. I don't know if that's desired.
An alternative would be to gate …

feat: add Termux support to `coins-ledger`

---

ledger/Cargo.toml

New version removes an unnecessary file modification on `build.rs`. This will also fix any build done by `docs.rs`, since it uses a read-only filesystem.
ref:
https://github.com/joshieDo/hidapi-rs/pull/5

chore: bump hidapi-rusb

---

core/src/lib.rs

Tarpaulin doesn't support `#[cfg_attr(tarpaulin, skip)]` anymore so running Tarpaulin required the `--avoid-cfg-tarpaulin` flag as described here: https://github.com/xd009642/tarpaulin#ignoring-code-in-files

Fix Tarpaulin attribute

---

bip32/Cargo.toml
bip32/src/derived.rs
bip32/src/enc.rs
bip32/src/lib.rs
bip32/src/macros.rs
bip32/src/prelude.rs
bip32/src/xkeys.rs

Upgrade motivated by https://github.com/gakonst/ethers-rs/issues/2158#issuecomment-1462927693.
The new `k256` v0.13 brought two breaking changes for the `bip32` crate:
The [`RecoverableSignature`](https://docs.rs/k256/0.11.6/k256/ecdsa/recoverable/struct.Signature.html) type has been removed which necessitated changes in the `inherit_signer` derive macro.  Following the [upgrade guide,](https://docs.rs/k256/latest/k256/ecdsa/index.html#upgrading-recoverable-signature-code-from-earlier-versions-of-k256) I've replaced the `DigestSigner<D, RecoverableSignature>` implementation with `DigestSigner<D, (Signature, RecoveryId)>` that uses the new [SigningKey::sign_digest_recoverable](https://docs.rs/ecdsa/0.16.0/x86_64-unknown-linux-gnu/ecdsa/signing/struct.SigningKey.html#method.sign_digest_recov …

chore: upgrade `k256` to 0.13

---

build.sh

Hey, 
I noticed the doc tests weren't running in the build script, so I added them there. Alternatively, removing the `--lib` flag on line 6 would run them as well, but maybe that would have unintended effects?

ci: run doctests in build script

---

.github/workflows/tests.yaml
.gitignore
bip32/Cargo.toml
bip32/src/lib.rs
bip39/Cargo.toml
bip39/src/lib.rs
bip39/src/mnemonic.rs
bip39/src/wordlist/mod.rs
core/Cargo.toml
core/src/enc.rs
ledger/Cargo.toml
ledger/src/transports/hid.rs
ledger/src/transports/mod.rs
ledger/src/transports/native.rs
ledger/src/transports/wasm.rs

Also updates CI and `getrandom`'s "js" feature for wasm targets.
Closes #121

chore: bump dependencies

---

bip39/Cargo.toml
ledger/Cargo.toml

```
Checking coins-ledger v0.9.0
error[E0433]: failed to resolve: could not find `Builder` in `runtime`
--> /home/doni/.cargo/registry/src/index.crates.io-6f17d22bba15001f/coins-ledger-0.9.0/src/transports/native/mod.rs:54:38
|
54 |             let rt = tokio::runtime::Builder::new_current_thread()
|                                      ^^^^^^^ could not find `Builder` in `runtime`
|
help: consider importing this struct
|
1  + use std::thread::Builder;
|
help: if you import `Builder`, refer to it directly
|
54 -             let rt = tokio::runtime::Builder::new_current_thread()
54 +             let rt = Builder::new_current_thread()
|
error[E0603]: module `runtime` is private
--> /home/doni/.cargo/registry/src/index.crates.io-6f17d22bba15001f/coins-ledger-0.9.0/src/transports/native/mod.rs …
```

fix(ledger): enable "rt" tokio feature

---

bip39/src/mnemonic.rs

Am I missing something or there is no way to create `Mnemonic` from existing `Entropy`? This PR adds a method to do so.

Add new mnemonic from entropy function

---

.github/workflows/tests.yaml

currently you are using an out of date version of the checkout action, this bumps you to keep in line with the latest major

chore(ci): bump checkout to current latest major

---

crates/bip32/src/xkeys.rs
crates/ledger/src/common.rs
crates/ledger/src/transports/native/hid.rs
crates/ledger/src/transports/wasm.rs
crates/ledger/tests/integration.rs

Fixes #137.
Submitting this patch optimistically. This contains a breaking change as a new field `cla` has been added.
Existing downstream applications would need to set `cla` to `0xe0` to continue to use `app-ethereum`.

fix: hard-coded CLA byte
